from _typeshed import Incomplete

class ROSException(Exception): ...
class ROSSerializationException(ROSException): ...
class ROSInitException(ROSException): ...
class ROSInterruptException(ROSException, KeyboardInterrupt): ...

class ROSTimeMovedBackwardsException(ROSInterruptException):
    time: Incomplete
    def __init__(self, time) -> None: ...

class ROSInternalException(Exception): ...
class TransportException(ROSInternalException): ...
class TransportTerminated(TransportException): ...
class TransportInitError(TransportException): ...
