from _typeshed import Incomplete
from rosgraph.names import ANYTYPE, GLOBALNS as GLOBALNS, REMAP as REMAP, make_global_ns as make_global_ns
from rospy.exceptions import ROSException as ROSException, ROSInitException as ROSInitException
from rospy.impl.validators import ParameterInvalid as ParameterInvalid

TOPIC_ANYTYPE = ANYTYPE
SERVICE_ANYTYPE = ANYTYPE

def isstring(s): ...
def canonicalize_name(name): ...
def reload_mappings(argv) -> None: ...
def initialize_mappings(node_name) -> None: ...
def resolve_name_without_node_name(name): ...
def get_mappings(): ...
def get_resolved_mappings(): ...
def resolve_name(name, caller_id: Incomplete | None = ...): ...
def remap_name(name, caller_id: Incomplete | None = ..., resolved: bool = ...): ...
def scoped_name(caller_id, name): ...
def valid_name_validator_resolved(param_name, param_value, caller_id): ...
def valid_name_validator_unresolved(param_name, param_value, caller_id): ...
def valid_name(param_name, resolve: bool = ...): ...
def global_name(param_name): ...
def get_namespace(): ...
def get_name(): ...
get_caller_id = get_name
