
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-08T14:57:02+0000",
 "dirty": true,
 "error": null,
 "full-revisionid": "e91593bb33b759ea8202928037aaad9b91467e76",
 "version": "0.3.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
