
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-08T19:01:58+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "c63431a7c13a54b1ee843f8f9ce29ce13dae976c",
 "version": "1.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
