
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-06T19:18:19+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "2d281cf5fa2d6defe378bc61683142405a1da169",
 "version": "0.54"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
