# Generated by Django 3.1.7 on 2021-05-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_squashed_0004_remove_contactpage_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Key words'),
        ),
    ]
