# Copyright 2023 Weavers @ Eternal Loom. All rights reserved.
#
# Use of this software is governed by the license that can be
# found in LICENSE file in the source repository.


WIP_MARKDOWN = """## We are still working on this feature. Appreciate your patience.

Meanwhile, here is a poem for you:

>_In a world where dreams take flight,_
>
>_Come back to us, be our guiding light._
>
>_Together we craft a future so grand,_
>
>_Your presence, the key to the wonders we've planned._

_Generated by ChatGPT_
"""

WIP_MESSAGE = """We are still working on this feature. Appreciate your patience.

Meanwhile, here is a poem for you:
In a world where dreams take flight,
Come back to us, be our guiding light.
Together we craft a future so grand,
Your presence, the key to the wonders we've planned.

- Generated by ChatGPT
"""

APP_INITIALIZED_MESSAGE = """Welcome to Smighty Agent Server (Sasy)!

This application has been initialized and ready to use. 
You can use the chat client interface at this [URL] or 
post your questions to the API endpoint at this [URL].
"""

APP_INITIALIZED_MESSAGE_HTML = """<html>
    <head>
        <title>Welcome to Smighty Agent Server (Sasy)</title>
    </head>
    <body>
        <h1>Welcome to Smighty Agent Server (Sasy)!</h1>
        <p>This application has been initialized and ready to use.</p>
        <p>You can use the chat client interface at this <a href="http://localhost:8000">URL</a> or</p>
        <p>post your questions to the API endpoint at this <a href="http://localhost:8000/docs">URL</a>.</p>
    </body>
</html>
"""
