VERSION_YEAR = 2023
VERSION_MONTH = int('12')
VERSION_DAY = int('11')
VERSION_HOUR = int('14')
VERSION_MINUTE = int('59')
MAJOR_VERSION = 1
MINOR_VERSION = 6
PATCH_VERSION = 202312111459
version_date = '2023/12/11 14:59'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
