# coding: utf-8

"""
    Ethos

    API for Ethos AI

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Optional
from pydantic import BaseModel, Field

class ProxyInferenceCreate(BaseModel):
    """
    ProxyInferenceCreate
    """
    id: Optional[Any] = Field(...)
    first_name: Optional[Any] = None
    last_name: Optional[Any] = None
    zipcode: Optional[Any] = None
    __properties = ["id", "first_name", "last_name", "zipcode"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ProxyInferenceCreate:
        """Create an instance of ProxyInferenceCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if id (nullable) is None
        # and __fields_set__ contains the field
        if self.id is None and "id" in self.__fields_set__:
            _dict['id'] = None

        # set to None if first_name (nullable) is None
        # and __fields_set__ contains the field
        if self.first_name is None and "first_name" in self.__fields_set__:
            _dict['first_name'] = None

        # set to None if last_name (nullable) is None
        # and __fields_set__ contains the field
        if self.last_name is None and "last_name" in self.__fields_set__:
            _dict['last_name'] = None

        # set to None if zipcode (nullable) is None
        # and __fields_set__ contains the field
        if self.zipcode is None and "zipcode" in self.__fields_set__:
            _dict['zipcode'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ProxyInferenceCreate:
        """Create an instance of ProxyInferenceCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ProxyInferenceCreate.parse_obj(obj)

        _obj = ProxyInferenceCreate.parse_obj({
            "id": obj.get("id"),
            "first_name": obj.get("first_name"),
            "last_name": obj.get("last_name"),
            "zipcode": obj.get("zipcode")
        })
        return _obj


