
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-06T13:42:21-0800",
 "dirty": true,
 "error": null,
 "full-revisionid": "d221e924ee48c3a5cefd3e22a9d082017cb014a2",
 "version": "0.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
