info = {"message": "fix: LEAP-449: remove Project model from migration path (#5157)", "commit": "dbd8ddd77e1e9be8d33115bc100f99e678450a63", "date": "2023/12/08 15:41:11", "branch": "", "version": "1.10.0.post0+0.gdbd8ddd.dirty"}

# This file is automatically generated by version.py
# Do not include it to git!
