
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-07T11:30:27-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "ca6da08b57c84b7f6c05db2a68378facca02194c",
 "version": "2.3.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
