# coding: utf-8

"""
    ARLAS Exploration API

    Explore the content of ARLAS collections  # noqa: E501

    OpenAPI spec version: 23.0.1
    Contact: contact@gisaia.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class CollectionDisplayNames(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'collection': 'str',
        'fields': 'dict(str, str)',
        'shape_columns': 'dict(str, str)'
    }

    attribute_map = {
        'collection': 'collection',
        'fields': 'fields',
        'shape_columns': 'shape_columns'
    }

    def __init__(self, collection=None, fields=None, shape_columns=None):  # noqa: E501
        """CollectionDisplayNames - a model defined in Swagger"""  # noqa: E501

        self._collection = None
        self._fields = None
        self._shape_columns = None
        self.discriminator = None

        if collection is not None:
            self.collection = collection
        if fields is not None:
            self.fields = fields
        if shape_columns is not None:
            self.shape_columns = shape_columns

    @property
    def collection(self):
        """Gets the collection of this CollectionDisplayNames.  # noqa: E501


        :return: The collection of this CollectionDisplayNames.  # noqa: E501
        :rtype: str
        """
        return self._collection

    @collection.setter
    def collection(self, collection):
        """Sets the collection of this CollectionDisplayNames.


        :param collection: The collection of this CollectionDisplayNames.  # noqa: E501
        :type: str
        """

        self._collection = collection

    @property
    def fields(self):
        """Gets the fields of this CollectionDisplayNames.  # noqa: E501


        :return: The fields of this CollectionDisplayNames.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._fields

    @fields.setter
    def fields(self, fields):
        """Sets the fields of this CollectionDisplayNames.


        :param fields: The fields of this CollectionDisplayNames.  # noqa: E501
        :type: dict(str, str)
        """

        self._fields = fields

    @property
    def shape_columns(self):
        """Gets the shape_columns of this CollectionDisplayNames.  # noqa: E501


        :return: The shape_columns of this CollectionDisplayNames.  # noqa: E501
        :rtype: dict(str, str)
        """
        return self._shape_columns

    @shape_columns.setter
    def shape_columns(self, shape_columns):
        """Sets the shape_columns of this CollectionDisplayNames.


        :param shape_columns: The shape_columns of this CollectionDisplayNames.  # noqa: E501
        :type: dict(str, str)
        """

        self._shape_columns = shape_columns

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CollectionDisplayNames, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CollectionDisplayNames):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
