from tc_data import tc_message
SUB_B.send(SUB_C, tc_message['SUBSCRIBE_0'])
SUB_C.wait_for_message('SUBSCRIBE')
SUB_D.send(SUB_E, tc_message['SUBSCRIBE_1'])
SUB_E.wait_for_message('SUBSCRIBE')
SUB_E.send(SUB_D, tc_message['SUBSCRIBE_2'])
SUB_D.wait_for_message('SUBSCRIBE')
SUB_F.send(SUB_G, tc_message['SUBSCRIBE_3'])
SUB_G.wait_for_message('SUBSCRIBE')
SUB_H.send(SUB_I, tc_message['200_4'])
SUB_I.wait_for_message('200 OK')
SUB_D.send(SUB_E, tc_message['200_5'])
SUB_E.wait_for_message('200 OK')
SUB_H.send(SUB_I, tc_message['NOTIFY_6'])
SUB_I.wait_for_message('NOTIFY')
SUB_I.send(SUB_H, tc_message['100_7'])
SUB_H.wait_for_message('100 Trying')
SUB_D.send(SUB_E, tc_message['NOTIFY_8'])
SUB_E.wait_for_message('NOTIFY')
SUB_E.send(SUB_D, tc_message['200_9'])
SUB_D.wait_for_message('200 OK')
SUB_C.send(SUB_B, tc_message['200_10'])
SUB_B.wait_for_message('200 OK')
SUB_E.send(SUB_D, tc_message['NOTIFY_11'])
SUB_D.wait_for_message('NOTIFY')
SUB_J.send(SUB_I, tc_message['NOTIFY_12'])
SUB_I.wait_for_message('NOTIFY')
SUB_J.send(SUB_I, tc_message['NOTIFY_13'])
SUB_I.wait_for_message('NOTIFY')
SUB_K.send(SUB_C, tc_message['OPTIONS_13'])
SUB_C.wait_for_message('OPTIONS')
SUB_F.send(SUB_G, tc_message['OPTIONS_14'])
SUB_G.wait_for_message('OPTIONS')
SUB_L.send(SUB_M, tc_message['200_15'])
SUB_M.wait_for_message('200 OK')
SUB_C.send(SUB_K, tc_message['200_16'])
SUB_K.wait_for_message('200 OK')
SUB_D.send(SUB_E, tc_message['408_17'])
SUB_E.wait_for_message('408 Request Timeout')
SUB_E.send(SUB_D, tc_message['408_18'])
SUB_D.wait_for_message('408 Request Timeout')
SUB_I.send(SUB_H, tc_message['408_18'])
SUB_H.wait_for_message('408 Request Timeout')
SUB_K.send(SUB_C, tc_message['OPTIONS_19'])
SUB_C.wait_for_message('OPTIONS')
SUB_F.send(SUB_G, tc_message['OPTIONS_19'])
SUB_G.wait_for_message('OPTIONS')
SUB_L.send(SUB_M, tc_message['200_19'])
SUB_M.wait_for_message('200 OK')
SUB_C.send(SUB_K, tc_message['200_19'])
SUB_K.wait_for_message('200 OK')
SUB_N.send(SUB_C, tc_message['SUBSCRIBE_19'])
SUB_C.wait_for_message('SUBSCRIBE')
SUB_D.send(SUB_E, tc_message['SUBSCRIBE_20'])
SUB_E.wait_for_message('SUBSCRIBE')
SUB_O.send(SUB_C, tc_message['INVITE_21'])
SUB_C.wait_for_message('INVITE')
SUB_E.send(SUB_D, tc_message['SUBSCRIBE_22'])
SUB_D.wait_for_message('SUBSCRIBE')
SUB_C.send(SUB_O, tc_message['100_23'])
SUB_O.wait_for_message('100 Trying')
SUB_D.send(SUB_E, tc_message['INVITE_24'])
SUB_E.wait_for_message('INVITE')
SUB_F.send(SUB_G, tc_message['SUBSCRIBE_25'])
SUB_G.wait_for_message('SUBSCRIBE')
SUB_H.send(SUB_I, tc_message['200_25'])
SUB_I.wait_for_message('200 OK')
SUB_D.send(SUB_E, tc_message['200_25'])
SUB_E.wait_for_message('200 OK')
SUB_E.send(SUB_D, tc_message['200_25'])
SUB_D.wait_for_message('200 OK')
SUB_C.send(SUB_N, tc_message['200_25'])
SUB_N.wait_for_message('200 OK')
SUB_H.send(SUB_I, tc_message['NOTIFY_25'])
SUB_I.wait_for_message('NOTIFY')
SUB_I.send(SUB_H, tc_message['100_26'])
SUB_H.wait_for_message('100 Trying')
SUB_D.send(SUB_E, tc_message['NOTIFY_26'])
SUB_E.wait_for_message('NOTIFY')
SUB_E.send(SUB_D, tc_message['INVITE_27'])
SUB_D.wait_for_message('INVITE')
SUB_D.send(SUB_E, tc_message['100_28'])
SUB_E.wait_for_message('100 Trying')
SUB_F.send(SUB_G, tc_message['INVITE_29'])
SUB_G.wait_for_message('INVITE')
SUB_P.send(SUB_Q, tc_message['100_30'])
SUB_Q.wait_for_message('100 Trying')
SUB_E.send(SUB_D, tc_message['NOTIFY_31'])
SUB_D.wait_for_message('NOTIFY')
SUB_J.send(SUB_I, tc_message['NOTIFY_32'])
SUB_I.wait_for_message('NOTIFY')
SUB_J.send(SUB_I, tc_message['NOTIFY_33'])
SUB_I.wait_for_message('NOTIFY')
SUB_E.send(SUB_D, tc_message['100_33'])
SUB_D.wait_for_message('100 Trying')
SUB_P.send(SUB_Q, tc_message['180_34'])
SUB_Q.wait_for_message('180 Ringing')
SUB_D.send(SUB_E, tc_message['180_35'])
SUB_E.wait_for_message('180 Ringing')
SUB_E.send(SUB_D, tc_message['180_36'])
SUB_D.wait_for_message('180 Ringing')
SUB_C.send(SUB_O, tc_message['180_37'])
SUB_O.wait_for_message('180 Ringing')
SUB_D.send(SUB_E, tc_message['408_38'])
SUB_E.wait_for_message('408 Request Timeout')
SUB_E.send(SUB_D, tc_message['408_38'])
SUB_D.wait_for_message('408 Request Timeout')
SUB_I.send(SUB_H, tc_message['408_38'])
SUB_H.wait_for_message('408 Request Timeout')
SUB_K.send(SUB_C, tc_message['OPTIONS_38'])
SUB_C.wait_for_message('OPTIONS')
SUB_F.send(SUB_G, tc_message['OPTIONS_38'])
SUB_G.wait_for_message('OPTIONS')
SUB_L.send(SUB_M, tc_message['200_38'])
SUB_M.wait_for_message('200 OK')
SUB_C.send(SUB_K, tc_message['200_38'])
SUB_K.wait_for_message('200 OK')
SUB_P.send(SUB_Q, tc_message['180_38'])
SUB_Q.wait_for_message('180 Ringing')
SUB_D.send(SUB_E, tc_message['180_39'])
SUB_E.wait_for_message('180 Ringing')
SUB_E.send(SUB_D, tc_message['180_40'])
SUB_D.wait_for_message('180 Ringing')
SUB_C.send(SUB_O, tc_message['180_41'])
SUB_O.wait_for_message('180 Ringing')
SUB_K.send(SUB_C, tc_message['OPTIONS_42'])
SUB_C.wait_for_message('OPTIONS')
SUB_F.send(SUB_G, tc_message['OPTIONS_42'])
SUB_G.wait_for_message('OPTIONS')
SUB_L.send(SUB_M, tc_message['200_42'])
SUB_M.wait_for_message('200 OK')
SUB_C.send(SUB_K, tc_message['200_42'])
SUB_K.wait_for_message('200 OK')
SUB_K.send(SUB_C, tc_message['OPTIONS_42'])
SUB_C.wait_for_message('OPTIONS')
SUB_F.send(SUB_G, tc_message['OPTIONS_42'])
SUB_G.wait_for_message('OPTIONS')
SUB_L.send(SUB_M, tc_message['200_42'])
SUB_M.wait_for_message('200 OK')
SUB_C.send(SUB_K, tc_message['200_42'])
SUB_K.wait_for_message('200 OK')
SUB_R.send(SUB_C, tc_message['SUBSCRIBE_42'])
SUB_C.wait_for_message('SUBSCRIBE')
SUB_D.send(SUB_E, tc_message['SUBSCRIBE_42'])
SUB_E.wait_for_message('SUBSCRIBE')
SUB_R.send(SUB_C, tc_message['SUBSCRIBE_42'])
SUB_C.wait_for_message('SUBSCRIBE')
SUB_D.send(SUB_E, tc_message['SUBSCRIBE_42'])
SUB_E.wait_for_message('SUBSCRIBE')
SUB_E.send(SUB_D, tc_message['SUBSCRIBE_43'])
SUB_D.wait_for_message('SUBSCRIBE')
SUB_F.send(SUB_G, tc_message['SUBSCRIBE_43'])
SUB_G.wait_for_message('SUBSCRIBE')
SUB_E.send(SUB_D, tc_message['SUBSCRIBE_43'])
SUB_D.wait_for_message('SUBSCRIBE')
SUB_F.send(SUB_G, tc_message['SUBSCRIBE_44'])
SUB_G.wait_for_message('SUBSCRIBE')
SUB_H.send(SUB_I, tc_message['200_44'])
SUB_I.wait_for_message('200 OK')
SUB_D.send(SUB_E, tc_message['200_44'])
SUB_E.wait_for_message('200 OK')
SUB_H.send(SUB_I, tc_message['NOTIFY_44'])
SUB_I.wait_for_message('NOTIFY')
SUB_I.send(SUB_H, tc_message['100_45'])
SUB_H.wait_for_message('100 Trying')
SUB_D.send(SUB_E, tc_message['NOTIFY_45'])
SUB_E.wait_for_message('NOTIFY')
SUB_H.send(SUB_I, tc_message['200_46'])
SUB_I.wait_for_message('200 OK')
SUB_D.send(SUB_E, tc_message['200_46'])
SUB_E.wait_for_message('200 OK')
SUB_H.send(SUB_I, tc_message['NOTIFY_46'])
SUB_I.wait_for_message('NOTIFY')
SUB_E.send(SUB_D, tc_message['200_47'])
SUB_D.wait_for_message('200 OK')
SUB_C.send(SUB_R, tc_message['200_47'])
SUB_R.wait_for_message('200 OK')
SUB_I.send(SUB_H, tc_message['100_47'])
SUB_H.wait_for_message('100 Trying')
SUB_D.send(SUB_E, tc_message['NOTIFY_47'])
SUB_E.wait_for_message('NOTIFY')
SUB_E.send(SUB_D, tc_message['NOTIFY_48'])
SUB_D.wait_for_message('NOTIFY')
SUB_J.send(SUB_I, tc_message['NOTIFY_49'])
SUB_I.wait_for_message('NOTIFY')
SUB_E.send(SUB_D, tc_message['200_50'])
SUB_D.wait_for_message('200 OK')
SUB_J.send(SUB_I, tc_message['NOTIFY_50'])
SUB_I.wait_for_message('NOTIFY')
SUB_C.send(SUB_R, tc_message['200_50'])
SUB_R.wait_for_message('200 OK')
SUB_E.send(SUB_D, tc_message['NOTIFY_50'])
SUB_D.wait_for_message('NOTIFY')
SUB_J.send(SUB_I, tc_message['NOTIFY_51'])
SUB_I.wait_for_message('NOTIFY')
SUB_J.send(SUB_I, tc_message['NOTIFY_52'])
SUB_I.wait_for_message('NOTIFY')
