from pathlib import Path

TESTS_FOLDER = Path(__file__).parent
GENERATED_FOLDER = TESTS_FOLDER / "generated"
INPUT_FOLDER = TESTS_FOLDER / "input_files"

INIT_PROJECT_INPUT_FOLDER = INPUT_FOLDER / "init_project"
GENERATED_PROJECT_FOLDER = GENERATED_FOLDER / "init_project"

SOURCES_PROJECT_INPUT_FOLDER = INPUT_FOLDER / "sources_project"

INPUT_PLBUILD_FOLDER = SOURCES_PROJECT_INPUT_FOLDER / "plbuild"
GENERATED_PLBUILD_FOLDER = GENERATED_PROJECT_FOLDER / "plbuild"

INPUT_SOURCES_FOLDER = INPUT_PLBUILD_FOLDER / "sources"
GENERATED_SOURCES_FOLDER = GENERATED_PLBUILD_FOLDER / "sources"

INPUT_DOCUMENT_SOURCES_FOLDER = INPUT_SOURCES_FOLDER / "document"
GENERATED_DOCUMENT_SOURCES_FOLDER = GENERATED_SOURCES_FOLDER / "document"

INPUT_PRESENTATION_SOURCES_FOLDER = INPUT_SOURCES_FOLDER / "presentation"
GENERATED_PRESENTATION_SOURCES_FOLDER = GENERATED_SOURCES_FOLDER / "presentation"

INPUT_DOCUMENTS_FOLDER = SOURCES_PROJECT_INPUT_FOLDER / "Documents"
GENERATED_DOCUMENTS_FOLDER = GENERATED_PROJECT_FOLDER / "Documents"

INPUT_SLIDES_FOLDER = SOURCES_PROJECT_INPUT_FOLDER / "Slides"
GENERATED_SLIDES_FOLDER = GENERATED_PROJECT_FOLDER / "Slides"

INPUT_HANDOUTS_FOLDER = SOURCES_PROJECT_INPUT_FOLDER / "Handouts"
GENERATED_HANDOUTS_FOLDER = GENERATED_PROJECT_FOLDER / "Handouts"

GENERATED_TEMPLATES_PATH = GENERATED_PLBUILD_FOLDER / "templates"