# Notrunc Recaptcha KEY
GOOGLE_RECAPTCHA_PUBLIC_KEY = '6Lf0II4nAAAAAPFaC_6vLK0mbECcDGRSQj3VaciT'
GOOGLE_RECAPTCHA_PRIVATE_KEY = '6Lf0II4nAAAAAEOhsDIAFbOg1PaN_qstaq4ecLM8'
GOOGLE_RECAPTCHA_SECRET_KEY = '6Lf0II4nAAAAAEOhsDIAFbOg1PaN_qstaq4ecLM8'

# Email sender
RECEIVE_EMAIL = 'newsletter@notrunc.cloud'
SERVER_EMAIL = 'noreply@notrunc.cloud'

CRISPY_TEMPLATE_PACK = 'bootstrap4'
