# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_cons.ipynb.

# %% auto 0
__all__ = ['e', 'F', 'BASE', 'SCHRS', 'SSYMS', 'ECHRS']

# %% ../nbs/03_cons.ipynb 3
from typing import get_args

# %% ../nbs/03_cons.ipynb 4
from .types import SignChr, SignSym, ExpoChr

# %% ../nbs/03_cons.ipynb 6
e: str = 'e'
F: str = 'F'

BASE: int = 10

SCHRS: str = ''.join(get_args(SignChr))
SSYMS: str = ''.join(get_args(SignSym))
ECHRS: str = ''.join(get_args(ExpoChr))
