# Generated by Django 3.1.7 on 2021-08-05 15:28

import coldcms.wagtail_customization.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('blog', '0003_blogindexpage_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTagGroupByBlogPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
            bases=(coldcms.wagtail_customization.mixins.ColdCMSPageMixin, 'wagtailcore.page'),
        ),
    ]
