# Generated by Django 3.1.7 on 2021-11-23 11:20

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210805_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindexpage',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True, default='', max_length=500, verbose_name='Intro'),
        ),
    ]
