# -*- coding: utf-8 -*-
# ------------------------------------------------------------------------------
# File   : myXcounit.py
#          (generated by XCoGen, XCOFDK Code Generator)
#
# Copyright (C) 2023 Farzad Safa
# All rights reserved.
# ------------------------------------------------------------------------------


# ------------------------------------------------------------------------------
# Import libs / modules
# ------------------------------------------------------------------------------
# fwapi
from xcofdk.fwapi.xcounit import XcoUnit
from xcofdk.fwapi.xcounit import XcoUnitProfile
from xcofdk.fwapi.xcounit import xlogif


# ------------------------------------------------------------------------------
# Interface
# ------------------------------------------------------------------------------
def GetMyXcoUnitProfile() -> XcoUnitProfile:
    """Return an instance of 'XcoUnitProfile' which can be passed to the c-tor of
    class 'MyXcoUnit' as depicted below:

        myMXU = MyXcoUnit(xcounitPrf_=GetMyXcoUnitProfile())
    """

    # create a default xcounit profile and properly set attribute values relevant for the returned instance of XcoUnitProfile
    res = XcoUnitProfile()

    res.aliasName = 'myXUnit'
    res.isSetupDisabled = True
    res.cyclicMaxProcessingTimespanMS = 40
    res.cyclicRunPauseTimespanMS = 120
    return res
#END GetMyXcoUnitProfile()


class MyXcoUnit(XcoUnit):

    __slots__ = []

    def __init__(self, xcounitPrf_ : XcoUnitProfile =None):
        XcoUnit.__init__(self, xcounitPrf_=xcounitPrf_)

    def RunXcoUnit(self) -> bool:
        xlogif.XLogInfo(f'Nothing to do, done run phase of xcounit {self.xcounitUniqueID}.')
        return False
    
    def TearDownXcoUnit(self) -> bool:
        xlogif.XLogInfo(f'Nothing to do, done tear down phase of xcounit {self.xcounitUniqueID}.')
        return True
    
#END class MyXcoUnit
