# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/01_nchr/01_core.ipynb.

# %% auto 0
__all__ = ['NIL', 'SPACE', 'DOT', 'DDOT', 'DOTDOT', 'CARET', 'COMMA', 'TILDA', 'SLASH', 'COLON', 'CLN', 'DCOLON', 'DCLN',
           'PERIOD', 'UNDERSCORE', 'SUNDER', 'DUNDER', 'ELLIPSE', 'DDDOT', 'DOTDOTDOT', 'STAR', 'ASTERICK', 'STARSTAR',
           'DSTAR', 'SUB_SUNDER']

# %% ../../nbs/01_nchr/01_core.ipynb 5
NIL = ''
SPACE = ' '

DOT = '.'
DDOT = DOTDOT = '..'

CARET = '^'
COMMA = ','
TILDA = '~'
SLASH = '/'
COLON = CLN = ':'
DCOLON = DCLN = '::'
PERIOD = DOT

UNDERSCORE = SUNDER = '_'
DUNDER = '__'
ELLIPSE = DDDOT = DOTDOTDOT = '...'

STAR = '*'
ASTERICK = STAR
STARSTAR = DSTAR = '**'

SUB_SUNDER = rf'{SUNDER}\1'
