
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-09T09:32:58+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "1074dc25c2de61fefebc5a89a57fd179fb2b5708",
 "version": "v1.2.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
