
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-06T18:08:13+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "39a78d44e73be2eb50c9e18d6cdc5064a76724f0",
 "version": "3.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
