# Generated by Django 4.0.10 on 2023-02-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_metric_contact_person_metric_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='type',
            field=models.CharField(choices=[('SQL_QUERY_V1', 'SQL_QUERY_V1'), ('SQL_QUERY_V2', 'SQL_QUERY_V2'), ('NOT_SUCCESS_V1', 'NOT_SUCCESS_V1'), ('SQL_SAGE_GATEWAY_V1', 'SQL_SAGE_GATEWAY_V1')], max_length=255),
        ),
    ]
