# Generated by Django 3.1.7 on 2021-04-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0005_auto_20200630_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqpage',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Key words'),
        ),
    ]
