# Copyright 2023 Weavers @ Eternal Loom. All rights reserved.
#
# Use of this software is governed by the license that can be
# found in LICENSE file in the source repository.


WIP_MARKDOWN = """## We are still working on this feature. Appreciate your patience.

Meanwhile, here is a poem for you:

>_In a world where dreams take flight,_
>
>_Come back to us, be our guiding light._
>
>_Together we craft a future so grand,_
>
>_Your presence, the key to the wonders we've planned._

_Generated by ChatGPT_
"""

WIP_MESSAGE = """We are still working on this feature. Appreciate your patience.

Meanwhile, here is a poem for you:
In a world where dreams take flight,
Come back to us, be our guiding light.
Together we craft a future so grand,
Your presence, the key to the wonders we've planned.

- Generated by ChatGPT
"""
