# Generated by Django 3.0.8 on 2021-02-23 16:23

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0008_variablescolors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footercolumn',
            name='links',
            field=wagtail.core.fields.StreamField([('links', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(help_text="Use this as the text of an external URL or if you want to override the Page's title", label='Link text', max_length=40, required=False)), ('custom_url', wagtail.core.blocks.CharBlock(label='External URL', required=False)), ('page', wagtail.core.blocks.PageChooserBlock(help_text='Ignored if the external URL is used', label='Link to an internal page', required=False)), ('extra_url', wagtail.core.blocks.CharBlock(default='', help_text='Use this to optionally append a #hash or querystring to the URL.', label='Append to URL', required=False)), ('blank', wagtail.core.blocks.BooleanBlock(label='Open link in a new tab', required=False))], icon='link'))], blank=True, null=True, verbose_name='Links'),
        ),
    ]
