
# This file was generated by 'versioneer.py' (0.26) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-07T11:04:12+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "2a8abe27ac8ca7dcd377fb306230d4f1393d0550",
 "version": "0.8.0.post0.dev2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
