# coding: utf-8

"""
    ARLAS Exploration API

    Explore the content of ARLAS collections  # noqa: E501

    OpenAPI spec version: 23.0.1
    Contact: contact@gisaia.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class CollectionOrganisations(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'owner': 'str',
        'shared': 'list[str]',
        'public': 'bool'
    }

    attribute_map = {
        'owner': 'owner',
        'shared': 'shared',
        'public': 'public'
    }

    def __init__(self, owner=None, shared=None, public=None):  # noqa: E501
        """CollectionOrganisations - a model defined in Swagger"""  # noqa: E501

        self._owner = None
        self._shared = None
        self._public = None
        self.discriminator = None

        if owner is not None:
            self.owner = owner
        if shared is not None:
            self.shared = shared
        if public is not None:
            self.public = public

    @property
    def owner(self):
        """Gets the owner of this CollectionOrganisations.  # noqa: E501


        :return: The owner of this CollectionOrganisations.  # noqa: E501
        :rtype: str
        """
        return self._owner

    @owner.setter
    def owner(self, owner):
        """Sets the owner of this CollectionOrganisations.


        :param owner: The owner of this CollectionOrganisations.  # noqa: E501
        :type: str
        """

        self._owner = owner

    @property
    def shared(self):
        """Gets the shared of this CollectionOrganisations.  # noqa: E501


        :return: The shared of this CollectionOrganisations.  # noqa: E501
        :rtype: list[str]
        """
        return self._shared

    @shared.setter
    def shared(self, shared):
        """Sets the shared of this CollectionOrganisations.


        :param shared: The shared of this CollectionOrganisations.  # noqa: E501
        :type: list[str]
        """

        self._shared = shared

    @property
    def public(self):
        """Gets the public of this CollectionOrganisations.  # noqa: E501


        :return: The public of this CollectionOrganisations.  # noqa: E501
        :rtype: bool
        """
        return self._public

    @public.setter
    def public(self, public):
        """Sets the public of this CollectionOrganisations.


        :param public: The public of this CollectionOrganisations.  # noqa: E501
        :type: bool
        """

        self._public = public

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CollectionOrganisations, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CollectionOrganisations):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
