
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "5a27f2473690515edf7c04f25d13d122a024cf0d",
 "version": "1.1.32"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
