from url_const import EMAIL_SERVICE_URL, PREPROCESS_SERVICE_URL, AZCOPY_SERVICE_URL, SKYLINE_SERVICE_URL, \
    TRIGGER_SERVICE_URL, FLIGHTS_RECORD_SERVICE_URL, WAR_E_SOLUTION_SKYLINE_SERVICE, WALL_E_SOLUTION_SKYLINE_SERVICE, \
    TGV_SERVICE_URL

from utils_consts import EMAIL_LIST_NAVAD, EMAIL_TEST_LIST, RABBIT_HOST
