from .CS2APY import fetch_all
from .CS2APY import fetch_global
from .CS2APY import fetch_europe
from .CS2APY import fetch_africa
from .CS2APY import fetch_asia
from .CS2APY import fetch_australia
from .CS2APY import fetch_china
from .CS2APY import fetch_northamerica
from .CS2APY import fetch_southamerica
from . import CS2APY