# Generated by Django 3.1.7 on 2021-04-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic_page', '0016_auto_20210412_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='genericpage',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Key words'),
        ),
    ]
