
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-11T12:40:47+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "35076a78030143121f74de3caac66006d0a42922",
 "version": "1.0.50"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
