
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-10T22:23:54+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "5cc94f46c3d9b973fde03a621ba080c5a4ec52e4",
 "version": "0.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
