# Campaign constants
DEFAULT_CAMPAIGN_ACOS = 30
DEFAULT_CAMPAIGN_NAME_PREFIX = "Radium10 - ST - "
DEFAULT_EXACT_ST_CAMPAIGN_NAME = DEFAULT_CAMPAIGN_NAME_PREFIX + "Exact - " + str(DEFAULT_CAMPAIGN_ACOS)
DEFAULT_PHRASE_ST_CAMPAIGN_NAME = DEFAULT_CAMPAIGN_NAME_PREFIX + "Phrase - " + str(DEFAULT_CAMPAIGN_ACOS)
DEFAULT_BROAD_ST_CAMPAIGN_NAME = DEFAULT_CAMPAIGN_NAME_PREFIX + "Broad - " + str(DEFAULT_CAMPAIGN_ACOS)
