
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-07T17:47:37+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "f46caab33937921de0a15ea6841da6fa73f51cd2",
 "version": "2.3.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
