PREFIXES_EL010_FIF = ["HIP2", "TEMP", "FROR", "INAN", "INPO", "HIP1"]

CHANNELS_EL010_FIF = [
    "HIP201-HIP202",
    "HIP202-HIP203",
    "HIP203-HIP204",
    "HIP204-HIP205",
    "HIP205-HIP206",
    "HIP206-HIP207",
    "HIP207-HIP208",
    "HIP208-HIP209",
    "HIP209-HIP210",
    "TEMP01-TEMP02",
    "TEMP02-TEMP03",
    "TEMP03-TEMP04",
    "TEMP04-TEMP05",
    "TEMP05-TEMP06",
    "TEMP06-TEMP07",
    "TEMP07-TEMP08",
    "TEMP08-TEMP09",
    "TEMP09-TEMP10",
    "FROR01-FROR02",
    "FROR02-FROR03",
    "FROR03-FROR04",
    "FROR04-FROR05",
    "FROR05-FROR06",
    "FROR06-FROR07",
    "FROR07-FROR08",
    "FROR08-FROR09",
    "FROR09-FROR10",
    "FROR10-FROR11",
    "FROR11-FROR12",
    "INAN01-INAN02",
    "INAN02-INAN03",
    "INAN03-INAN04",
    "INAN04-INAN05",
    "INAN05-INAN06",
    "INAN06-INAN07",
    "INAN07-INAN08",
    "INAN08-INAN09",
    "INAN09-INAN10",
    "INAN10-INAN11",
    "INAN11-INAN12",
    "INPO01-INPO02",
    "INPO02-INPO03",
    "INPO03-INPO04",
    "INPO04-INPO05",
    "INPO05-INPO06",
    "INPO06-INPO07",
    "INPO07-INPO08",
    "INPO08-INPO09",
    "INPO09-INPO10",
    "INPO10-INPO11",
    "INPO11-INPO12",
    "HIP101-HIP102",
    "HIP102-HIP103",
    "HIP103-HIP104",
    "HIP104-HIP105",
    "HIP105-HIP106",
    "HIP106-HIP107",
    "HIP107-HIP108",
    "HIP108-HIP109",
    "HIP109-HIP110",
    "HIP110-HIP111",
    "HIP111-HIP112",
]

LABELS_EL010 = [
    "Hip21",
    "Hip22",
    "Hip23",
    "Hip24",
    "Hip25",
    "Hip26",
    "Hip27",
    "Hip28",
    "Hip29",
    "Hip210",
    "Temp1",
    "Temp2",
    "Temp3",
    "Temp4",
    "Temp5",
    "Temp6",
    "Temp7",
    "Temp8",
    "Temp9",
    "Temp10",
    "FrOr1",
    "FrOr2",
    "FrOr3",
    "FrOr4",
    "FrOr5",
    "FrOr6",
    "FrOr7",
    "FrOr8",
    "FrOr9",
    "FrOr10",
    "FrOr11",
    "FrOr12",
    "In An1",
    "In An2",
    "In An3",
    "In An4",
    "In An5",
    "In An6",
    "In An7",
    "In An8",
    "In An9",
    "In An10",
    "In An11",
    "In An12",
    "InPo1",
    "InPo2",
    "InPo3",
    "InPo4",
    "InPo5",
    "InPo6",
    "InPo7",
    "InPo8",
    "InPo9",
    "InPo10",
    "InPo11",
    "InPo12",
    "Hip11",
    "Hip12",
    "Hip13",
    "Hip14",
    "Hip15",
    "Hip16",
    "Hip17",
    "Hip18",
    "Hip19",
    "Hip110",
    "Hip111",
    "Hip112",
]

DATASET_PATHS_EL010 = [
    "/traces/raw/Hip21",
    "/traces/raw/Hip22",
    "/traces/raw/Hip23",
    "/traces/raw/Hip24",
    "/traces/raw/Hip25",
    "/traces/raw/Hip26",
    "/traces/raw/Hip27",
    "/traces/raw/Hip28",
    "/traces/raw/Hip29",
    "/traces/raw/Hip210",
    "/traces/raw/Temp1",
    "/traces/raw/Temp2",
    "/traces/raw/Temp3",
    "/traces/raw/Temp4",
    "/traces/raw/Temp5",
    "/traces/raw/Temp6",
    "/traces/raw/Temp7",
    "/traces/raw/Temp8",
    "/traces/raw/Temp9",
    "/traces/raw/Temp10",
    "/traces/raw/FrOr1",
    "/traces/raw/FrOr2",
    "/traces/raw/FrOr3",
    "/traces/raw/FrOr4",
    "/traces/raw/FrOr5",
    "/traces/raw/FrOr6",
    "/traces/raw/FrOr7",
    "/traces/raw/FrOr8",
    "/traces/raw/FrOr9",
    "/traces/raw/FrOr10",
    "/traces/raw/FrOr11",
    "/traces/raw/FrOr12",
    "/traces/raw/In An1",
    "/traces/raw/In An2",
    "/traces/raw/In An3",
    "/traces/raw/In An4",
    "/traces/raw/In An5",
    "/traces/raw/In An6",
    "/traces/raw/In An7",
    "/traces/raw/In An8",
    "/traces/raw/In An9",
    "/traces/raw/In An10",
    "/traces/raw/In An11",
    "/traces/raw/In An12",
    "/traces/raw/InPo1",
    "/traces/raw/InPo2",
    "/traces/raw/InPo3",
    "/traces/raw/InPo4",
    "/traces/raw/InPo5",
    "/traces/raw/InPo6",
    "/traces/raw/InPo7",
    "/traces/raw/InPo8",
    "/traces/raw/InPo9",
    "/traces/raw/InPo10",
    "/traces/raw/InPo11",
    "/traces/raw/InPo12",
    "/traces/raw/Hip11",
    "/traces/raw/Hip12",
    "/traces/raw/Hip13",
    "/traces/raw/Hip14",
    "/traces/raw/Hip15",
    "/traces/raw/Hip16",
    "/traces/raw/Hip17",
    "/traces/raw/Hip18",
    "/traces/raw/Hip19",
    "/traces/raw/Hip110",
    "/traces/raw/Hip111",
    "/traces/raw/Hip112",
]

LEAD_PREFIXES_EL010 = ["Hip2", "Temp", "FrOr", "In An", "InPo", "Hip1"]

DATASET_PATHS_SZ2 = [
    "/traces/raw/Amy1",
    "/traces/raw/Amy10",
    "/traces/raw/Amy11",
    "/traces/raw/Amy12",
    "/traces/raw/Amy2",
    "/traces/raw/Amy3",
    "/traces/raw/Amy4",
    "/traces/raw/Amy5",
    "/traces/raw/Amy6",
    "/traces/raw/Amy7",
    "/traces/raw/Amy8",
    "/traces/raw/Amy9",
    "/traces/raw/Ant_In1",
    "/traces/raw/Ant_In10",
    "/traces/raw/Ant_In11",
    "/traces/raw/Ant_In12",
    "/traces/raw/Ant_In13",
    "/traces/raw/Ant_In14",
    "/traces/raw/Ant_In15",
    "/traces/raw/Ant_In16",
    "/traces/raw/Ant_In17",
    "/traces/raw/Ant_In18",
    "/traces/raw/Ant_In2",
    "/traces/raw/Ant_In3",
    "/traces/raw/Ant_In4",
    "/traces/raw/Ant_In5",
    "/traces/raw/Ant_In6",
    "/traces/raw/Ant_In7",
    "/traces/raw/Ant_In8",
    "/traces/raw/Ant_In9",
    "/traces/raw/Ent1",
    "/traces/raw/Ent10",
    "/traces/raw/Ent11",
    "/traces/raw/Ent12",
    "/traces/raw/Ent2",
    "/traces/raw/Ent3",
    "/traces/raw/Ent4",
    "/traces/raw/Ent5",
    "/traces/raw/Ent6",
    "/traces/raw/Ent7",
    "/traces/raw/Ent8",
    "/traces/raw/Ent9",
    "/traces/raw/G_ant1",
    "/traces/raw/G_ant2",
    "/traces/raw/G_ant3",
    "/traces/raw/G_ant4",
    "/traces/raw/G_ant5",
    "/traces/raw/G_ant6",
    "/traces/raw/G_ant7",
    "/traces/raw/G_ant8",
    "/traces/raw/G_post1",
    "/traces/raw/G_post2",
    "/traces/raw/G_post3",
    "/traces/raw/G_post4",
    "/traces/raw/G_post5",
    "/traces/raw/G_post6",
    "/traces/raw/G_post7",
    "/traces/raw/G_post8",
    "/traces/raw/G_sup1",
    "/traces/raw/G_sup2",
    "/traces/raw/G_sup3",
    "/traces/raw/G_sup4",
    "/traces/raw/G_sup5",
    "/traces/raw/G_sup6",
    "/traces/raw/G_sup7",
    "/traces/raw/G_sup8",
    "/traces/raw/Hip1",
    "/traces/raw/Hip10",
    "/traces/raw/Hip11",
    "/traces/raw/Hip12",
    "/traces/raw/Hip2",
    "/traces/raw/Hip3",
    "/traces/raw/Hip4",
    "/traces/raw/Hip5",
    "/traces/raw/Hip6",
    "/traces/raw/Hip7",
    "/traces/raw/Hip8",
    "/traces/raw/Hip9",
    "/traces/raw/OF_L1",
    "/traces/raw/OF_L10",
    "/traces/raw/OF_L11",
    "/traces/raw/OF_L12",
    "/traces/raw/OF_L2",
    "/traces/raw/OF_L3",
    "/traces/raw/OF_L4",
    "/traces/raw/OF_L5",
    "/traces/raw/OF_L6",
    "/traces/raw/OF_L7",
    "/traces/raw/OF_L8",
    "/traces/raw/OF_L9",
    "/traces/raw/aHip1",
    "/traces/raw/aHip10",
    "/traces/raw/aHip11",
    "/traces/raw/aHip12",
    "/traces/raw/aHip2",
    "/traces/raw/aHip3",
    "/traces/raw/aHip4",
    "/traces/raw/aHip5",
    "/traces/raw/aHip6",
    "/traces/raw/aHip7",
    "/traces/raw/aHip8",
    "/traces/raw/aHip9",
    "/traces/raw/pos_In1",
    "/traces/raw/pos_In10",
    "/traces/raw/pos_In11",
    "/traces/raw/pos_In12",
    "/traces/raw/pos_In13",
    "/traces/raw/pos_In14",
    "/traces/raw/pos_In15",
    "/traces/raw/pos_In16",
    "/traces/raw/pos_In17",
    "/traces/raw/pos_In18",
    "/traces/raw/pos_In2",
    "/traces/raw/pos_In3",
    "/traces/raw/pos_In4",
    "/traces/raw/pos_In5",
    "/traces/raw/pos_In6",
    "/traces/raw/pos_In7",
    "/traces/raw/pos_In8",
    "/traces/raw/pos_In9",
]

LEAD_PREFIXES_SZ2 = [
    "Hip",
    "aHip",
    "Amy",
    "Ant_In",
    "Ent",
    "G_ant",
    "G_post",
    "G_sup",
    "OF_L",
    "pos_In",
]

DATASET_PATHS_EL003 = [
    "EEG Amy01-REF",
    "EEG Amy02-REF",
    "EEG Amy03-REF",
    "EEG Amy04-REF",
    "EEG Amy05-REF",
    "EEG Amy06-REF",
    "EEG Amy07-REF",
    "EEG Amy08-REF",
    "EEG A.Hip01-REF",
    "EEG A.Hip02-REF",
    "EEG A.Hip03-REF",
    "EEG A.Hip04-REF",
    "EEG A.Hip05-REF",
    "EEG A.Hip06-REF",
    "EEG A.Hip07-REF",
    "EEG A.Hip08-REF",
    "EEG Les.A.01-REF",
    "EEG Les.A.02-REF",
    "EEG Les.A.03-REF",
    "EEG Les.A.04-REF",
    "EEG Les.A.05-REF",
    "EEG Les.A.06-REF",
    "EEG Les.A.07-REF",
    "EEG Les.A.08-REF",
    "EEG Les.I.01-REF",
    "EEG Les.I.02-REF",
    "EEG Les.I.03-REF",
    "EEG Les.I.04-REF",
    "EEG Les.I.05-REF",
    "EEG Les.I.06-REF",
    "EEG Les.I.07-REF",
    "EEG Les.I.08-REF",
    "EEG Les.P.01-REF",
    "EEG Les.P.02-REF",
    "EEG Les.P.03-REF",
    "EEG Les.P.04-REF",
    "EEG Les.P.05-REF",
    "EEG Les.P.06-REF",
    "EEG Les.P.07-REF",
    "EEG Les.P.08-REF",
    "EEG Les.S.01-REF",
    "EEG Les.S.02-REF",
    "EEG Les.S.03-REF",
    "EEG Les.S.04-REF",
    "EEG Les.S.05-REF",
    "EEG Les.S.06-REF",
    "EEG Les.S.07-REF",
    "EEG Les.S.08-REF",
    "EEG Mid.H.01-REF",
    "EEG Mid.H.02-REF",
    "EEG Mid.H.03-REF",
    "EEG Mid.H.04-REF",
    "EEG Mid.H.05-REF",
    "EEG Mid.H.06-REF",
    "EEG Mid.H.07-REF",
    "EEG Mid.H.08-REF",
    "EEG T1_ant.01-RE",
    "EEG T1.ant.02-RE",
    "EEG T1.ant.03-RE",
    "EEG T1.ant.04-RE",
    "EEG T1.ant.05-RE",
    "EEG T1.ant.06-RE",
    "EEG T1.ant.07-RE",
    "EEG T1.ant.08-RE",
]

DATASET_PATHS_EL003_BIP = [
    "/traces/raw_bipolar/lead/Amy/Amy01-Amy02",
    "/traces/raw_bipolar/lead/Amy/Amy02-Amy03",
    "/traces/raw_bipolar/lead/Amy/Amy03-Amy04",
    "/traces/raw_bipolar/lead/Amy/Amy04-Amy05",
    "/traces/raw_bipolar/lead/Amy/Amy05-Amy06",
    "/traces/raw_bipolar/lead/Amy/Amy06-Amy07",
    "/traces/raw_bipolar/lead/Amy/Amy07-Amy08",
    "/traces/raw_bipolar/lead/HippA/HippA01-HippA02",
    "/traces/raw_bipolar/lead/HippA/HippA02-HippA03",
    "/traces/raw_bipolar/lead/HippA/HippA03-HippA04",
    "/traces/raw_bipolar/lead/HippA/HippA04-HippA05",
    "/traces/raw_bipolar/lead/HippA/HippA05-HippA06",
    "/traces/raw_bipolar/lead/HippA/HippA06-HippA07",
    "/traces/raw_bipolar/lead/HippA/HippA07-HippA08",
    "/traces/raw_bipolar/lead/LesA/LesA01-LesA02",
    "/traces/raw_bipolar/lead/LesA/LesA02-LesA03",
    "/traces/raw_bipolar/lead/LesA/LesA03-LesA04",
    "/traces/raw_bipolar/lead/LesA/LesA04-LesA05",
    "/traces/raw_bipolar/lead/LesA/LesA05-LesA06",
    "/traces/raw_bipolar/lead/LesA/LesA06-LesA07",
    "/traces/raw_bipolar/lead/LesA/LesA07-LesA08",
    "/traces/raw_bipolar/lead/LesI/LesI01-LesI02",
    "/traces/raw_bipolar/lead/LesI/LesI02-LesI03",
    "/traces/raw_bipolar/lead/LesI/LesI03-LesI04",
    "/traces/raw_bipolar/lead/LesI/LesI04-LesI05",
    "/traces/raw_bipolar/lead/LesI/LesI05-LesI06",
    "/traces/raw_bipolar/lead/LesI/LesI06-LesI07",
    "/traces/raw_bipolar/lead/LesI/LesI07-LesI08",
    "/traces/raw_bipolar/lead/LesP/LesP01-LesP02",
    "/traces/raw_bipolar/lead/LesP/LesP02-LesP03",
    "/traces/raw_bipolar/lead/LesP/LesP03-LesP04",
    "/traces/raw_bipolar/lead/LesP/LesP04-LesP05",
    "/traces/raw_bipolar/lead/LesP/LesP05-LesP06",
    "/traces/raw_bipolar/lead/LesP/LesP06-LesP07",
    "/traces/raw_bipolar/lead/LesP/LesP07-LesP08",
    "/traces/raw_bipolar/lead/LesS/LesS01-LesS02",
    "/traces/raw_bipolar/lead/LesS/LesS02-LesS03",
    "/traces/raw_bipolar/lead/LesS/LesS03-LesS04",
    "/traces/raw_bipolar/lead/LesS/LesS04-LesS05",
    "/traces/raw_bipolar/lead/LesS/LesS05-LesS06",
    "/traces/raw_bipolar/lead/LesS/LesS06-LesS07",
    "/traces/raw_bipolar/lead/LesS/LesS07-LesS08",
    "/traces/raw_bipolar/lead/HippM/HippM01-HippM02",
    "/traces/raw_bipolar/lead/HippM/HippM02-HippM03",
    "/traces/raw_bipolar/lead/HippM/HippM03-HippM04",
    "/traces/raw_bipolar/lead/HippM/HippM04-HippM05",
    "/traces/raw_bipolar/lead/HippM/HippM05-HippM06",
    "/traces/raw_bipolar/lead/HippM/HippM06-HippM07",
    "/traces/raw_bipolar/lead/HippM/HippM07-HippM08",
    "/traces/raw_bipolar/lead/T1Ant/T1Ant01-T1Ant02",
    "/traces/raw_bipolar/lead/T1Ant/T1Ant02-T1Ant03",
    "/traces/raw_bipolar/lead/T1Ant/T1Ant03-T1Ant04",
    "/traces/raw_bipolar/lead/T1Ant/T1Ant04-T1Ant05",
    "/traces/raw_bipolar/lead/T1Ant/T1Ant05-T1Ant06",
    "/traces/raw_bipolar/lead/T1Ant/T1Ant06-T1Ant07",
    "/traces/raw_bipolar/lead/T1Ant/T1Ant07-T1Ant08",
]

LEAD_PREFIXES_EL003 = [
    "Amy",
    "HippA",
    "LesA",
    "LesI",
    "LesP",
    "LesS",
    "HippM",
    "T1Ant",
]

DATASET_PATHS_008 = [
    "/traces/raw/AL1",
    "/traces/raw/AL2",
    "/traces/raw/AL3",
    "/traces/raw/AL4",
    "/traces/raw/AL5",
    "/traces/raw/AL6",
    "/traces/raw/AL7",
    "/traces/raw/AL8",
    "/traces/raw/AL9",
    "/traces/raw/AL10",
    "/traces/raw/AL11",
    "/traces/raw/AL12",
    "/traces/raw/aHL1",
    "/traces/raw/aHL2",
    "/traces/raw/aHL3",
    "/traces/raw/aHL4",
    "/traces/raw/aHL5",
    "/traces/raw/aHL6",
    "/traces/raw/aHL7",
    "/traces/raw/aHL8",
    "/traces/raw/aHL9",
    "/traces/raw/aHL10",
    "/traces/raw/aHL11",
    "/traces/raw/aHL12",
    "/traces/raw/OFR1",
    "/traces/raw/OFR2",
    "/traces/raw/OFR3",
    "/traces/raw/OFR4",
    "/traces/raw/OFR5",
    "/traces/raw/OFR6",
    "/traces/raw/OFR7",
    "/traces/raw/OFR8",
    "/traces/raw/OFR9",
    "/traces/raw/OFR10",
    "/traces/raw/OFR11",
    "/traces/raw/OFR12",
    "/traces/raw/OFR13",
    "/traces/raw/OFR14",
    "/traces/raw/OFR15",
    "/traces/raw/CingR1",
    "/traces/raw/CingR2",
    "/traces/raw/CingR9",
    "/traces/raw/CingR10",
    "/traces/raw/CingR11",
    "/traces/raw/CingR12",
    "/traces/raw/AR1",
    "/traces/raw/AR2",
    "/traces/raw/AR3",
    "/traces/raw/AR4",
    "/traces/raw/AR6",
    "/traces/raw/AR7",
    "/traces/raw/AR8",
    "/traces/raw/AR9",
    "/traces/raw/AR10",
    "/traces/raw/AR11",
    "/traces/raw/AR12",
    "/traces/raw/aHR1",
    "/traces/raw/aHR2",
    "/traces/raw/aHR3",
    "/traces/raw/aHR4",
    "/traces/raw/aHR5",
    "/traces/raw/aHR6",
    "/traces/raw/aHR7",
    "/traces/raw/aHR8",
    "/traces/raw/aHR9",
    "/traces/raw/aHR10",
    "/traces/raw/aHR11",
    "/traces/raw/aHR12",
    "/traces/raw/EntR1",
    "/traces/raw/EntR2",
    "/traces/raw/EntR3",
    "/traces/raw/EntR4",
    "/traces/raw/EntR5",
    "/traces/raw/EntR6",
    "/traces/raw/EntR7",
    "/traces/raw/EntR8",
    "/traces/raw/EntR9",
    "/traces/raw/EntR10",
    "/traces/raw/pHR1",
    "/traces/raw/pHR2",
    "/traces/raw/pHR3",
    "/traces/raw/pHR4",
    "/traces/raw/pHR5",
    "/traces/raw/pHR6",
    "/traces/raw/pHR7",
    "/traces/raw/pHR8",
    "/traces/raw/pHR9",
    "/traces/raw/pHR10",
    "/traces/raw/pHR11",
    "/traces/raw/pHR12",
    "/traces/raw/aIR1",
    "/traces/raw/aIR2",
    "/traces/raw/aIR3",
    "/traces/raw/aIR4",
    "/traces/raw/aIR5",
    "/traces/raw/aIR6",
    "/traces/raw/aIR7",
    "/traces/raw/aIR8",
    "/traces/raw/aIR9",
    "/traces/raw/aIR10",
    "/traces/raw/aIR11",
    "/traces/raw/aIR12",
    "/traces/raw/aIR13",
    "/traces/raw/aIR14",
    "/traces/raw/aIR15",
    "/traces/raw/aIR16",
    "/traces/raw/aIR17",
    "/traces/raw/aIR18",
    "/traces/raw/pIR1",
    "/traces/raw/pIR3",
    "/traces/raw/pIR4",
    "/traces/raw/pIR5",
    "/traces/raw/pIR6",
    "/traces/raw/pIR7",
    "/traces/raw/pIR8",
    "/traces/raw/pIR9",
    "/traces/raw/pIR10",
    "/traces/raw/pIR11",
    "/traces/raw/pIR12",
    "/traces/raw/pIR13",
    "/traces/raw/pIR14",
    "/traces/raw/pIR15",
    "/traces/raw/pIR16",
    "/traces/raw/pIR17",
]
LEAD_PREFIXES_008 = [
    "AL",
    "aHL",
    "OFR",
    "CingR",
    "AR",
    "aHR",
    "EntR",
    "pHR",
    "aIR",
    "pIR",
]

DATASET_PATHS_007 = [
    "/traces/raw/aHL1",
    "/traces/raw/aHL2",
    "/traces/raw/aHL3",
    "/traces/raw/aHL4",
    "/traces/raw/aHL5",
    "/traces/raw/aHL6",
    "/traces/raw/aHL7",
    "/traces/raw/aHL8",
    "/traces/raw/aHL9",
    "/traces/raw/aHL10",
    "/traces/raw/aHL11",
    "/traces/raw/aHL12",
    "/traces/raw/pHL1",
    "/traces/raw/pHL2",
    "/traces/raw/pHL3",
    "/traces/raw/pHL4",
    "/traces/raw/pHL5",
    "/traces/raw/pHL6",
    "/traces/raw/pHL7",
    "/traces/raw/pHL8",
    "/traces/raw/pHL9",
    "/traces/raw/pHL10",
    "/traces/raw/pHL11",
    "/traces/raw/pHL12",
    "/traces/raw/AmL1",
    "/traces/raw/AmL2",
    "/traces/raw/AmL3",
    "/traces/raw/AmL4",
    "/traces/raw/AmL5",
    "/traces/raw/AmL6",
    "/traces/raw/AmL7",
    "/traces/raw/AmL8",
    "/traces/raw/AmL9",
    "/traces/raw/AmL10",
    "/traces/raw/AmL11",
    "/traces/raw/AmL12",
    "/traces/raw/EnL1",
    "/traces/raw/EnL2",
    "/traces/raw/EnL3",
    "/traces/raw/EnL4",
    "/traces/raw/EnL5",
    "/traces/raw/EnL6",
    "/traces/raw/EnL7",
    "/traces/raw/EnL8",
    "/traces/raw/EnL9",
    "/traces/raw/EnL10",
    "/traces/raw/EnL11",
    "/traces/raw/EnL12",
    "/traces/raw/OFL1",
    "/traces/raw/OFL2",
    "/traces/raw/OFL3",
    "/traces/raw/OFL4",
    "/traces/raw/OFL5",
    "/traces/raw/OFL6",
    "/traces/raw/OFL7",
    "/traces/raw/OFL8",
    "/traces/raw/OFL9",
    "/traces/raw/OFL10",
    "/traces/raw/OFL11",
    "/traces/raw/OFL12",
    "/traces/raw/OFL13",
    "/traces/raw/OFL14",
    "/traces/raw/OFL15",
    "/traces/raw/FpoL1",
    "/traces/raw/FpoL2",
    "/traces/raw/FpoL3",
    "/traces/raw/FpoL4",
    "/traces/raw/FpoL5",
    "/traces/raw/FpoL6",
    "/traces/raw/FpoL7",
    "/traces/raw/FpoL8",
    "/traces/raw/FpoL9",
    "/traces/raw/FpoL10",
    "/traces/raw/FpoL11",
    "/traces/raw/FpoL12",
    "/traces/raw/CinL1",
    "/traces/raw/CinL2",
    "/traces/raw/CinL3",
    "/traces/raw/CinL4",
    "/traces/raw/CinL5",
    "/traces/raw/CinL6",
    "/traces/raw/CinL7",
    "/traces/raw/CinL8",
    "/traces/raw/CinL9",
    "/traces/raw/CinL10",
    "/traces/raw/CinL11",
    "/traces/raw/CinL12",
    "/traces/raw/LinL1",
    "/traces/raw/LinL2",
    "/traces/raw/LinL3",
    "/traces/raw/LinL4",
    "/traces/raw/LinL5",
    "/traces/raw/LinL6",
    "/traces/raw/LinL7",
    "/traces/raw/LinL8",
    "/traces/raw/LinL9",
    "/traces/raw/LinL10",
    "/traces/raw/LinL11",
    "/traces/raw/LinL12",
    "/traces/raw/LinL13",
    "/traces/raw/LinL14",
    "/traces/raw/LinL15",
    "/traces/raw/HR1",
    "/traces/raw/HR2",
    "/traces/raw/HR3",
    "/traces/raw/HR4",
    "/traces/raw/HR5",
    "/traces/raw/HR6",
    "/traces/raw/HR7",
    "/traces/raw/HR8",
    "/traces/raw/HR9",
    "/traces/raw/HR10",
    "/traces/raw/HR11",
    "/traces/raw/HR12",
    "/traces/raw/EnR1",
    "/traces/raw/EnR2",
    "/traces/raw/EnR3",
    "/traces/raw/EnR4",
    "/traces/raw/EnR5",
    "/traces/raw/EnR6",
    "/traces/raw/EnR7",
    "/traces/raw/EnR8",
    "/traces/raw/EnR9",
    "/traces/raw/EnR10",
    "/traces/raw/EnR11",
]

LEAD_PREFIXES_007 = [
    "aHL",
    "pHL",
    "AmL",
    "EnL",
    "OFL",
    "FpoL",
    "CinL",
    "LinL",
    "HR",
    "EnR",
]

DATASET_PATHS_006 = [
    "/traces/raw/APr1",
    "/traces/raw/APr2",
    "/traces/raw/APr3",
    "/traces/raw/APr4",
    "/traces/raw/APr5",
    "/traces/raw/APr6",
    "/traces/raw/APr7",
    "/traces/raw/APr8",
    "/traces/raw/APr9",
    "/traces/raw/APr10",
    "/traces/raw/APr11",
    "/traces/raw/APr12",
    "/traces/raw/aHR1",
    "/traces/raw/aHR2",
    "/traces/raw/aHR3",
    "/traces/raw/aHR4",
    "/traces/raw/aHR5",
    "/traces/raw/aHR6",
    "/traces/raw/aHR7",
    "/traces/raw/aHR8",
    "/traces/raw/aHR9",
    "/traces/raw/aHR10",
    "/traces/raw/aHR11",
    "/traces/raw/aHR12",
    "/traces/raw/aLR1",
    "/traces/raw/aLR2",
    "/traces/raw/aLR3",
    "/traces/raw/aLR4",
    "/traces/raw/aLR5",
    "/traces/raw/aLR6",
    "/traces/raw/aLR7",
    "/traces/raw/aLR8",
    "/traces/raw/aLR9",
    "/traces/raw/aLR10",
    "/traces/raw/aLR11",
    "/traces/raw/aLR12",
    "/traces/raw/aLR13",
    "/traces/raw/aLR14",
    "/traces/raw/aLR15",
    "/traces/raw/aLR16",
    "/traces/raw/aLR17",
    "/traces/raw/aLR18",
    "/traces/raw/CGr1",
    "/traces/raw/CGr2",
    "/traces/raw/CGr3",
    "/traces/raw/CGr4",
    "/traces/raw/CGr5",
    "/traces/raw/CGr6",
    "/traces/raw/CGr7",
    "/traces/raw/CGr8",
    "/traces/raw/CGr9",
    "/traces/raw/CGr10",
    "/traces/raw/CGr11",
    "/traces/raw/CGr12",
    "/traces/raw/CGr13",
    "/traces/raw/CGr14",
    "/traces/raw/CGr15",
    "/traces/raw/EGr1",
    "/traces/raw/EGr2",
    "/traces/raw/EGr3",
    "/traces/raw/EGr4",
    "/traces/raw/EGr5",
    "/traces/raw/EGr6",
    "/traces/raw/EGr7",
    "/traces/raw/EGr8",
    "/traces/raw/EGr9",
    "/traces/raw/EGr10",
    "/traces/raw/EGr11",
    "/traces/raw/EGr12",
    "/traces/raw/LGr1",
    "/traces/raw/LGr2",
    "/traces/raw/LGr3",
    "/traces/raw/LGr4",
    "/traces/raw/LGr5",
    "/traces/raw/LGr6",
    "/traces/raw/LGr7",
    "/traces/raw/LGr8",
    "/traces/raw/LGr9",
    "/traces/raw/LGr10",
    "/traces/raw/LGr11",
    "/traces/raw/LGr12",
    "/traces/raw/OFR1",
    "/traces/raw/OFR2",
    "/traces/raw/OFR3",
    "/traces/raw/OFR4",
    "/traces/raw/OFR5",
    "/traces/raw/OFR6",
    "/traces/raw/OFR7",
    "/traces/raw/OFR8",
    "/traces/raw/OFR9",
    "/traces/raw/OFR10",
    "/traces/raw/OFR11",
    "/traces/raw/OFR12",
    "/traces/raw/OFR13",
    "/traces/raw/OFR14",
    "/traces/raw/OFR15",
    "/traces/raw/pHR1",
    "/traces/raw/pHR2",
    "/traces/raw/pHR3",
    "/traces/raw/pHR4",
    "/traces/raw/pHR5",
    "/traces/raw/pHR6",
    "/traces/raw/pHR7",
    "/traces/raw/pHR8",
    "/traces/raw/pHR9",
    "/traces/raw/pHR10",
    "/traces/raw/pHR11",
    "/traces/raw/pHR12",
    "/traces/raw/plR1",
    "/traces/raw/plR2",
    "/traces/raw/plR3",
    "/traces/raw/plR4",
    "/traces/raw/plR5",
    "/traces/raw/plR6",
    "/traces/raw/plR7",
    "/traces/raw/plR8",
    "/traces/raw/plR9",
    "/traces/raw/plR10",
    "/traces/raw/plR11",
    "/traces/raw/plR12",
    "/traces/raw/plR13",
    "/traces/raw/plR14",
    "/traces/raw/plR15",
    "/traces/raw/plR16",
    "/traces/raw/plR17",
    "/traces/raw/plR18",
    "/traces/raw/AL1",
    "/traces/raw/AL2",
    "/traces/raw/AL3",
    "/traces/raw/AL4",
    "/traces/raw/AL5",
    "/traces/raw/AL6",
    "/traces/raw/AL7",
    "/traces/raw/AL8",
    "/traces/raw/AL9",
    "/traces/raw/AL10",
    "/traces/raw/AL11",
    "/traces/raw/AL12",
    "/traces/raw/aHL1",
    "/traces/raw/aHL2",
    "/traces/raw/aHL3",
    "/traces/raw/aHL4",
    "/traces/raw/aHL5",
    "/traces/raw/aHL6",
    "/traces/raw/aHL7",
    "/traces/raw/aHL8",
    "/traces/raw/aHL9",
    "/traces/raw/aHL10",
    "/traces/raw/aHL11",
    "/traces/raw/aHL12",
]

LEAD_PREFIXES_006 = [
    "APr",
    "aHR",
    "aLR",
    "CGr",
    "EGr",
    "LGr",
    "OFR",
    "pHR",
    "plR",
    "AL",
    "aHL",
]

CHANNEL_NAMES_005 = [
    "A_L1",
    "A_L2",
    "A_L3",
    "A_L4",
    "A_L5",
    "A_L6",
    "A_L7",
    "A_L8",
    "A_L9",
    "A_L10",
    "A_L11",
    "A_L12",
    "aH_L1",
    "aH_L2",
    "aH_L3",
    "aH_L4",
    "aH_L5",
    "aH_L6",
    "aH_L7",
    "aH_L8",
    "aH_L9",
    "aH_L10",
    "aH_L11",
    "aH_L12",
    "pH_L1",
    "pH_L2",
    "pH_L3",
    "pH_L4",
    "pH_L5",
    "pH_L6",
    "pH_L7",
    "pH_L8",
    "pH_L9",
    "pH_L10",
    "pH_L11",
    "pH_L12",
    "Ent_L1",
    "Ent_L2",
    "Ent_L3",
    "Ent_L4",
    "Ent_L5",
    "Ent_L6",
    "Ent_L7",
    "Ent_L8",
    "Ent_L9",
    "Ent_L10",
    "Ent_L11",
    "Ent_L12",
    "A_R1",
    "A_R2",
    "A_R3",
    "A_R4",
    "A_R5",
    "A_R6",
    "A_R7",
    "A_R8",
    "A_R9",
    "A_R10",
    "A_R11",
    "A_R12",
    "aH_R1",
    "aH_R2",
    "aH_R3",
    "aH_R4",
    "aH_R5",
    "aH_R6",
    "aH_R7",
    "aH_R8",
    "aH_R9",
    "aH_R10",
    "aH_R11",
    "aH_R12",
]

LEAD_PREFIXES_005 = [
    "A_L",
    "aH_L",
    "pH_L",
    "Ent_L",
    "A_R",
    "aH_R",
]
