
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-08T16:31:41+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "a72ba48e419a2e17a1f254a51044f527d4f659db",
 "version": "1.1.3a3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
