# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/02_nlit/11_tree.ipynb.

# %% auto 0
__all__ = ['BASE', 'LEAF', 'TREE', 'ROOT', 'NODE', 'TREE_SPACE', 'TREE_BRANCH', 'TREE_TEE', 'TREE_LAST']

# %% ../../nbs/02_nlit/11_tree.ipynb 6
BASE = 'base'
LEAF = 'leaf'
TREE = 'tree'
ROOT = 'root'
NODE = 'node'

# %% ../../nbs/02_nlit/11_tree.ipynb 8
TREE_SPACE : str = '    '
TREE_BRANCH: str = '│   '    
TREE_TEE   : str = '├── '
TREE_LAST  : str = '└── '
