{
    'name': 'Coopdevs Meta UX Improvements',
    'version': '14.0.1.0.0',
    'category': 'Extra Tools',
    'summary': 'Module to automate the installation of a set of modules',
    'sequence': '10',
    'author': 'Coopdevs',
    'maintainer': 'Coopdevs',
    'website': 'https://www.coopdevs.org',
    'depends': [
        'web_search_with_and',
        'web_remember_tree_column_width',
        'web_refresher',
        'web_group_expand',
        'web_advanced_search',
        'web_access_rule_buttons',
        'web_widget_datepicker_fulloptions',
        'web_widget_numeric_step',
        'web_widget_open_tab',
        'base_archive_date',
        'base_custom_filter',
        'base_export_manager',
        'base_optional_quick_create',
        'base_user_locale',
        'date_range',
        'date_range_account',
        'filter_multi_user',
        'mass_editing',
        'sequence_reset_period',
        'report_qweb_element_page_visibility'
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
