
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-06T11:38:39-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "dd1b9ca12a4e4666271ae9724ba39966cb025c9d",
 "version": "0.1.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
