
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-09T15:29:36+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "83d6087aded97a9b2d8a641f216f4b231feb985d",
 "version": "3.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
