from _typeshed import Incomplete
from threading import Lock as Lock

class MasterProxy:
    target: Incomplete
    def __init__(self, uri) -> None: ...
    def __getattr__(self, key): ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, val) -> None: ...
    def search_param(self, key): ...
    def get_param_cached(self, key): ...
    def __delitem__(self, key) -> None: ...
    def __contains__(self, key) -> bool: ...
    def __iter__(self): ...
