# Generated by Django 3.0.8 on 2021-02-03 18:22

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('site_settings', '0007_auto_20200730_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariablesColors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('black', colorfield.fields.ColorField(default='#0a0a0a', max_length=18, verbose_name='Noire')),
                ('black_bis', colorfield.fields.ColorField(default='#121212', max_length=18, verbose_name='Second noire')),
                ('black_ter', colorfield.fields.ColorField(default='#242424', max_length=18, verbose_name='Troisième noire')),
                ('grey_darker', colorfield.fields.ColorField(default='#363636', max_length=18, verbose_name='Gris très foncé')),
                ('grey_dark', colorfield.fields.ColorField(default='#4a4a4a', max_length=18, verbose_name='Gris foncé')),
                ('grey', colorfield.fields.ColorField(default='#7a7a7a', max_length=18, verbose_name='Gris')),
                ('grey_light', colorfield.fields.ColorField(default='#b5b5b5', max_length=18, verbose_name='Gris clair')),
                ('grey_lighter', colorfield.fields.ColorField(default='#dbdbdb', max_length=18, verbose_name='Gris très clair')),
                ('grey_lightest', colorfield.fields.ColorField(default='#ededed', max_length=18, verbose_name='Gris le plus clair')),
                ('white', colorfield.fields.ColorField(default='#ffffff', max_length=18, verbose_name='Blanc')),
                ('white_bis', colorfield.fields.ColorField(default='#fafafa', max_length=18, verbose_name='Second blanc')),
                ('white_ter', colorfield.fields.ColorField(default='#f5f5f5', max_length=18, verbose_name='Troisième blanc')),
                ('orange', colorfield.fields.ColorField(default='#ff470f', max_length=18, verbose_name='Orange')),
                ('yellow', colorfield.fields.ColorField(default='#ffe08a', max_length=18, verbose_name='Jaune')),
                ('green', colorfield.fields.ColorField(default='#48c78e', max_length=18, verbose_name='Vert')),
                ('turquoise', colorfield.fields.ColorField(default='#00d1b2', max_length=18, verbose_name='Turquoise')),
                ('cyan', colorfield.fields.ColorField(default='#3e8ed0', max_length=18, verbose_name='Cyan')),
                ('blue', colorfield.fields.ColorField(default='#485fc7', max_length=18, verbose_name='Bleu')),
                ('purple', colorfield.fields.ColorField(default='#b86bff', max_length=18, verbose_name='Violet')),
                ('red', colorfield.fields.ColorField(default='#f14668', max_length=18, verbose_name='Rouge')),
                ('primary', colorfield.fields.ColorField(default='#38b2db', max_length=18, verbose_name='Principale')),
                ('info', colorfield.fields.ColorField(default='#3e8ed0', max_length=18, verbose_name='Info')),
                ('success', colorfield.fields.ColorField(default='#48c78e', max_length=18, verbose_name='Succès')),
                ('warning', colorfield.fields.ColorField(default='#ffe08a', max_length=18, verbose_name='Attention')),
                ('danger', colorfield.fields.ColorField(default='#f14668', max_length=18, verbose_name='Erreur')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'verbose_name': 'Couleurs',
            },
        ),
    ]
