from _typeshed import Incomplete

class ParamServerCache:
    lock: Incomplete
    d: Incomplete
    notifier: Incomplete
    def __init__(self) -> None: ...
    def delete(self, key) -> None: ...
    def set_notifier(self, notifier) -> None: ...
    def update(self, key, value) -> None: ...
    def set(self, key, value) -> None: ...
    def get(self, key): ...

def get_param_server_cache(): ...
