
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-08T14:22:17+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "ada9b43bd1d3c2d38733ef483a0d4f75f674baa8",
 "version": "5.2.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
