
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-07T10:51:02+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "81dcf89591650c480776e28d268250633d580324",
 "version": "v1.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
