
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-07T17:13:55+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "985c2df214c87cdbcddac24c1540b81b99f84ea7",
 "version": "5.3.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
