# coding: utf-8

"""
    Ethos

    API for Ethos AI

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Optional
from pydantic import BaseModel, Field
from ethos.ethos_client.models.workflow_template_data import WorkflowTemplateData

class WorkflowTemplate(BaseModel):
    """
    WorkflowTemplate
    """
    object: Optional[Any] = Field(...)
    id: Optional[Any] = Field(...)
    name: Optional[Any] = Field(...)
    workspace: Optional[Any] = Field(...)
    created_at: Optional[Any] = Field(...)
    created_by: Optional[Any] = Field(...)
    yaml: Optional[Any] = Field(...)
    data: WorkflowTemplateData = Field(...)
    __properties = ["object", "id", "name", "workspace", "created_at", "created_by", "yaml", "data"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> WorkflowTemplate:
        """Create an instance of WorkflowTemplate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of data
        if self.data:
            _dict['data'] = self.data.to_dict()
        # set to None if object (nullable) is None
        # and __fields_set__ contains the field
        if self.object is None and "object" in self.__fields_set__:
            _dict['object'] = None

        # set to None if id (nullable) is None
        # and __fields_set__ contains the field
        if self.id is None and "id" in self.__fields_set__:
            _dict['id'] = None

        # set to None if name (nullable) is None
        # and __fields_set__ contains the field
        if self.name is None and "name" in self.__fields_set__:
            _dict['name'] = None

        # set to None if workspace (nullable) is None
        # and __fields_set__ contains the field
        if self.workspace is None and "workspace" in self.__fields_set__:
            _dict['workspace'] = None

        # set to None if created_at (nullable) is None
        # and __fields_set__ contains the field
        if self.created_at is None and "created_at" in self.__fields_set__:
            _dict['created_at'] = None

        # set to None if created_by (nullable) is None
        # and __fields_set__ contains the field
        if self.created_by is None and "created_by" in self.__fields_set__:
            _dict['created_by'] = None

        # set to None if yaml (nullable) is None
        # and __fields_set__ contains the field
        if self.yaml is None and "yaml" in self.__fields_set__:
            _dict['yaml'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> WorkflowTemplate:
        """Create an instance of WorkflowTemplate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return WorkflowTemplate.parse_obj(obj)

        _obj = WorkflowTemplate.parse_obj({
            "object": obj.get("object"),
            "id": obj.get("id"),
            "name": obj.get("name"),
            "workspace": obj.get("workspace"),
            "created_at": obj.get("created_at"),
            "created_by": obj.get("created_by"),
            "yaml": obj.get("yaml"),
            "data": WorkflowTemplateData.from_dict(obj.get("data")) if obj.get("data") is not None else None
        })
        return _obj


