# coding: utf-8

"""
    Ethos

    API for Ethos AI

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Optional
from pydantic import BaseModel, Field

class WorkflowCreate(BaseModel):
    """
    WorkflowCreate
    """
    project_id: Optional[Any] = Field(...)
    name: Optional[Any] = Field(...)
    workflow_template_id: Optional[Any] = Field(...)
    __properties = ["project_id", "name", "workflow_template_id"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> WorkflowCreate:
        """Create an instance of WorkflowCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # set to None if project_id (nullable) is None
        # and __fields_set__ contains the field
        if self.project_id is None and "project_id" in self.__fields_set__:
            _dict['project_id'] = None

        # set to None if name (nullable) is None
        # and __fields_set__ contains the field
        if self.name is None and "name" in self.__fields_set__:
            _dict['name'] = None

        # set to None if workflow_template_id (nullable) is None
        # and __fields_set__ contains the field
        if self.workflow_template_id is None and "workflow_template_id" in self.__fields_set__:
            _dict['workflow_template_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> WorkflowCreate:
        """Create an instance of WorkflowCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return WorkflowCreate.parse_obj(obj)

        _obj = WorkflowCreate.parse_obj({
            "project_id": obj.get("project_id"),
            "name": obj.get("name"),
            "workflow_template_id": obj.get("workflow_template_id")
        })
        return _obj


