
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-11T12:25:22-0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "0fa4a12210642e58d318fea6fdfe61559f564c5f",
 "version": "2.26.0rc9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
