import genpy
from _typeshed import Incomplete

class AnyMsg(genpy.Message):
    def __init__(self, *args) -> None: ...
    def serialize(self, buff) -> None: ...
    def deserialize(self, str): ...

def args_kwds_to_message(data_class, args, kwds): ...
def serialize_message(b, seq, msg) -> None: ...
def deserialize_messages(b, msg_queue, data_class, queue_size: Incomplete | None = ..., max_msgs: Incomplete | None = ..., start: int = ...) -> None: ...
