# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/04_enum/04_cell.ipynb.

# %% auto 0
__all__ = ['FilterMatrixFiles']

# %% ../../nbs/04_enum/04_cell.ipynb 4
from enum import StrEnum

# %% ../../nbs/04_enum/04_cell.ipynb 5
from ..nlit.exts import EXT_H5, EXT_MTX, EXT_TSV
from ..nlit.cell import ADATA, MATRIX, BARCODES, FEATURES

# %% ../../nbs/04_enum/04_cell.ipynb 7
class FilterMatrixFiles(StrEnum):
    MATRIX = f'{MATRIX}{EXT_MTX}'
    BARCODES = f'{BARCODES}{EXT_TSV}'
    FEATURES = f'{FEATURES}{EXT_TSV}'
    ADATA = f'{ADATA}{EXT_H5}'
