
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-08T14:53:22-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "90d7d8373fb45b4d74ae2e889c7276419b546f93",
 "version": "2.2.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
