
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-11T17:29:07+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "7ff443f5c4569643a5ea9c8caa2dfdf3b3f724ef",
 "version": "0.0.19"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
