
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2023-12-09T12:03:51+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "a29f5c0392a926343bf1e8c58ea70bcf15db4e43",
 "version": "0.2.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
