# Generated by Django 3.2.5 on 2021-10-04 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_newsletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='craeted_at',
            new_name='created_at',
        ),
    ]
