# coding: utf-8

"""
    Nomos API

    For more information on the Nomos API, please refer to the documentation at https://getnomos.com/docs/api.

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nomos.api_resources.models.provider_name import ProviderName


class TestProviderName(unittest.TestCase):
    """ProviderName unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testProviderName(self):
        """Test ProviderName"""
        # inst = ProviderName()


if __name__ == "__main__":
    unittest.main()
