# coding: utf-8

"""
    Nomos API

    For more information on the Nomos API, please refer to the documentation at https://getnomos.com/docs/api.

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nomos.api_resources.models.project_version_get_active_request import (
    ProjectVersionGetActiveRequest,
)


class TestProjectVersionGetActiveRequest(unittest.TestCase):
    """ProjectVersionGetActiveRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectVersionGetActiveRequest:
        """Test ProjectVersionGetActiveRequest
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `ProjectVersionGetActiveRequest`
        """
        model = ProjectVersionGetActiveRequest()
        if include_optional:
            return ProjectVersionGetActiveRequest(
                project_id = '',
                branch_name = 'default'
            )
        else:
            return ProjectVersionGetActiveRequest(
                project_id = '',
        )
        """

    def testProjectVersionGetActiveRequest(self):
        """Test ProjectVersionGetActiveRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
