# coding: utf-8

"""
    Nomos API

    For more information on the Nomos API, please refer to the documentation at https://getnomos.com/docs/api.

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nomos.api_resources.models.dynamic_parameters import DynamicParameters


class TestDynamicParameters(unittest.TestCase):
    """DynamicParameters unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DynamicParameters:
        """Test DynamicParameters
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `DynamicParameters`
        """
        model = DynamicParameters()
        if include_optional:
            return DynamicParameters(
                type = 'dynamic',
                value = ''
            )
        else:
            return DynamicParameters(
                type = 'dynamic',
                value = '',
        )
        """

    def testDynamicParameters(self):
        """Test DynamicParameters"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
