# coding: utf-8

"""
    Nomos API

    For more information on the Nomos API, please refer to the documentation at https://getnomos.com/docs/api.

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nomos.api_resources.models.open_ai_function_call_object import (
    OpenAIFunctionCallObject,
)


class TestOpenAIFunctionCallObject(unittest.TestCase):
    """OpenAIFunctionCallObject unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OpenAIFunctionCallObject:
        """Test OpenAIFunctionCallObject
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `OpenAIFunctionCallObject`
        """
        model = OpenAIFunctionCallObject()
        if include_optional:
            return OpenAIFunctionCallObject(
                name = ''
            )
        else:
            return OpenAIFunctionCallObject(
                name = '',
        )
        """

    def testOpenAIFunctionCallObject(self):
        """Test OpenAIFunctionCallObject"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
