# coding: utf-8

"""
    Nomos API

    For more information on the Nomos API, please refer to the documentation at https://getnomos.com/docs/api.

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nomos.api_resources.models.open_ai_completion_prompt import OpenAICompletionPrompt


class TestOpenAICompletionPrompt(unittest.TestCase):
    """OpenAICompletionPrompt unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OpenAICompletionPrompt:
        """Test OpenAICompletionPrompt
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `OpenAICompletionPrompt`
        """
        model = OpenAICompletionPrompt()
        if include_optional:
            return OpenAICompletionPrompt(
                provider_name = 'openai',
                provider_function = 'completion',
                content = ''
            )
        else:
            return OpenAICompletionPrompt(
                provider_name = 'openai',
                provider_function = 'completion',
                content = '',
        )
        """

    def testOpenAICompletionPrompt(self):
        """Test OpenAICompletionPrompt"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
