# coding: utf-8

"""
    Nomos API

    For more information on the Nomos API, please refer to the documentation at https://getnomos.com/docs/api.

    The version of the OpenAPI document: 0.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from nomos.api_resources.models.open_ai_chat_completion_params_function_call import (
    OpenAIChatCompletionParamsFunctionCall,
)


class TestOpenAIChatCompletionParamsFunctionCall(unittest.TestCase):
    """OpenAIChatCompletionParamsFunctionCall unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OpenAIChatCompletionParamsFunctionCall:
        """Test OpenAIChatCompletionParamsFunctionCall
        include_option is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `OpenAIChatCompletionParamsFunctionCall`
        """
        model = OpenAIChatCompletionParamsFunctionCall()
        if include_optional:
            return OpenAIChatCompletionParamsFunctionCall(
                name = ''
            )
        else:
            return OpenAIChatCompletionParamsFunctionCall(
                name = '',
        )
        """

    def testOpenAIChatCompletionParamsFunctionCall(self):
        """Test OpenAIChatCompletionParamsFunctionCall"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
