# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/05_util/03_exts.ipynb.

# %% auto 0
__all__ = ['istar', 'isgz', 'istargz', 'istarball']

# %% ../../nbs/05_util/03_exts.ipynb 4
from typing import Optional

# %% ../../nbs/05_util/03_exts.ipynb 5
from .path import hasext
from nlit.exts import EXT_TAR, EXT_GZ, EXT_TAR_GZ

# %% ../../nbs/05_util/03_exts.ipynb 6
def istar(file: str) -> bool:
    return hasext(file, EXT_TAR)

def isgz(file: str) -> bool:
    return hasext(file, EXT_GZ)

def istargz(file: str) -> bool:
    return hasext(file, EXT_TAR_GZ)

def istarball(file: str) -> bool:
    return istar(file) or istargz(file)
