# Generated by Django 4.1.1 on 2022-12-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_source_meta_connector_source_meta_db_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metric',
            name='type',
            field=models.CharField(choices=[('TECHNICAL', 'TECHNICAL'), ('PROCESS', 'PROCESS')], default='TECHNICAL', max_length=255),
        ),
    ]
